# Generated by Django 5.1.2 on 2024-10-17 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('journal', models.CharField(max_length=2000)),
                ('teeth', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('sleep', models.PositiveIntegerField()),
                ('skincare', models.PositiveIntegerField()),
                ('gym_hours', models.PositiveIntegerField()),
                ('coding_hours', models.PositiveIntegerField()),
                ('pages_read', models.PositiveIntegerField()),
            ],
        ),
    ]
